---
# tasks file for ansible-do-droplet

- name: main | create droplet
  digital_ocean_droplet:
    name: "{{ inventory_hostname }}"
    region: "{{ droplet_region }}"
    size: "{{ hostvars[inventory_hostname].size | default(droplet_size) }}"
    image: "{{ hostvars[inventory_hostname].image | default(droplet_image) }}"
    tags: "{{ hostvars[inventory_hostname].tags | default(droplet_tags) | default([]) }}"
    user_data: "{{ '#cloud-config\n' + hostvars[inventory_hostname].user_data | default(droplet_user_data) | default('') | to_nice_yaml }}"
    ipv6: "{{ hostvars[inventory_hostname].ipv6 | default(droplet_ipv6) | default(false) }}"
    state: present
    unique_name: true
    oauth_token: "{{ digital_ocean_token }}"
  register: created_droplet
  delegate_to: localhost

- name: main | add to inventory
  add_host:
    groups: "{{ droplet_group | default('newly_created') }}"
    name: "{{ created_droplet.data.ip_address }}"
  delegate_to: localhost
  when: droplet_return_name is not defined

- name: main | add to inventory
  add_host:
    groups: "{{ droplet_group | default('newly_created') }}"
    name: "{{ inventory_hostname+'.'+ droplet_domain | default(hostvars[inventory_hostname].domain) }}"
  delegate_to: localhost
  when: droplet_return_name is defined