---
dependency:
  name: galaxy
driver:
  name: digitalocean
lint:
  name: yamllint
  options:
    config-data:
      ignore: venv
platforms:
  - name: test-drop1
    region_id: nyc1
    size_id: 512mb
    image_id: centos-7-x64

provisioner:
  name: ansible
  inventory:
    host_vars:
      test-drop1:
        size: 512mb
        image: centos-7-x64
        tags:
          - test
        user_data:
          users:
            - name: phil
              groups: wheel
              sudo: ['ALL=(ALL) NOPASSWD:ALL']
              ssh-authorized-keys:
                - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCtSJ+1DjiVNvOS6TAH9IO/jBkXdYcjRBoQnAM3TtznrwCILEx216D8vmuLhK/QxSg1jV1gBmepovKa7W3QuUwPSHAQwhPvdDA4oAYJKQug5uI/IHnz9lST/ICOvdAnTklwUmYnTShg+dSosNCjusahpKLHvZ4eIkshC4eo2Vw2RRUtP9PEF0XX14qBw2hK3SXgtzLAViuHTFb8pFLFzF1V3pKfRFiEOUpZ3fCtLzDEPac46bmtybgFmqZadCX84Rxf9SNl91PLC8BqFo/vjnPZ6/6qn3pY54jsvs4CgGeIRBx8pDeAtZvDel2picd39iZJk2zUD1Lg7oTI4801aylIFhjLnP89POmNXAEgE1SJin5TWgQ9MCiNnHYQ3MhWOpowSB4hlfT9botBptPKDbcBJLu91YM1IVdlUUzh+1hxkBh/k/cd6swR9hvF7J1QIKMV9YY1eO90ksIveKv5cOwTPutwjlatoJr7OD/962v/Caddk+W37yQfCHZO7//E7xVGSFHtnIx/CH7HfOchMLcmno5zLnnvc7YUErE41dvX9IOIDnUBjjQyc6EI6y66mQYXls+xpuluL1+7cv5fDZDeRUTr1WWWwNoikgDPFvWVvpAa+RmTpaXNORPYZYdNMY9zD3tclEO3fVBjwHHs5uTxXk7CqDfOgQN+ObtCdSU2kQ== phil@bove.online
                - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDXNQL/oXi65Q0s0wMbzxzVIqMTBW+EnIZwlOa0naQeKj/uYagSOFsHb9OoPWqCxAVbkP1JSSiQvazBc0cnZkeT441RgYW5Nn3dr6P/6xeZ7b+UqhIbmuGf0NffZgLBeCByMXWgxONC0cE9SMKFbTyaMQgBG1GY0CsCXhvndOz2S9W4louU88DN/4s5Tot8ICm/BFIlW7nNolz4s0HSn1SYfZOOdV0OdKuGS2tYek75uTGUXVjvvj8s1VX/JJSbte115lbw+rP2EusrqWRmdzPTJ4/LgE3pPtCna66DuTYj5LLVUHr6Y4AdFJzCvgwb7Xo1Dwpi9CGHPa3RFJLXMK1atuLvNuP5SmwTaABJdljNIHXckwhZ+CKI9Ujn+D1hj4pbw8edJyvBq6Vam3mcfE9fbyjF6LSQlJ9urH5hKNbx9q01QE1TW8xZLATQ4XVnXrJeb3Dlc59dQvpV7yrVC0N2dcaORW1yeTDhvf+JvVVXBTbuwQHsJPkYkgnblPZ/jMM= phil@ammo-box
            - name: root
              lock_passwd: true
          runcmd:
            - sed -i 's/PasswordAuthentication yes/PasswordAuthentication no/g' /etc/ssh/sshd_config
            - sed -i 's/#PubkeyAuthentication yes/PubkeyAuthentication yes/g' /etc/ssh/sshd_config
            - service sshd restart
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
scenario:
  name: default
  converge_sequence:
    - dependency
    - lint
    - converge
    - create
    - verify
    - destroy
  test_sequence:
    - destroy
    - dependency
    - lint
    - converge
    - create
    - verify
    - destroy
